### ISSUE TITLE
Double taxonomy link in breadcrumb

### ISSUE THREAD

**Issue by ghost** [hugomodo/hugomodo-best-motherfucking-website#5]
When visiting a post through the categories list page I have a double Categories link in the breadcrumb.

Frontmatter example of posts:
```yaml
---
title: "Goals"
description: "Given a person opposite of you..."
date: 2022-12-09T19:24:19+01:00
categories:
  - Thoughts
include_toc: false
draft: false
---
```

Screenshot:
![Screenshot 2022-12-11 184259](https://user-images.githubusercontent.com/51471948/206919776-db543994-28b6-4cd7-8ccb-fe97d7004df3.png)

Sorry in advance if this is not detailed enough, I don't know how to explain it better.
